entry_version = 1
name = "caffeinate"
kind = "widget"
latest = "0.1.4"
description = "Keep macOS awake indefinitely or for a selected duration."
categories = ["system", "utilities"]

[source]
repository = "https://github.com/easybar-app/widgets"

[[versions]]
version = "0.1.0"
archive = "https://github.com/easybar-app/widgets/releases/download/caffeinate-v0.1.0/caffeinate-0.1.0.tar.gz"
sha256 = "a2f644258a62553e4808485e7631b15122d939460942f20d6de3cdb380415ed0"

[[versions]]
version = "0.1.1"
archive = "https://github.com/easybar-app/widgets/releases/download/caffeinate-v0.1.1/caffeinate-0.1.1.tar.gz"
sha256 = "f346daecc38f6d777a5d0fe1f69515926ecc1d3f42c8e5ea99eca095c0f330cc"

[[versions]]
version = "0.1.3"
archive = "https://github.com/easybar-app/widgets/releases/download/caffeinate-v0.1.3/caffeinate-0.1.3.tar.gz"
sha256 = "d8334cc09b361ff95a45ba648ba13fbec3cf558c378392a2affaa3ee0e18c38c"

[[versions]]
version = "0.1.4"
archive = "https://github.com/easybar-app/widgets/releases/download/caffeinate-v0.1.4/caffeinate-0.1.4.tar.gz"
sha256 = "3a4f31fde02655454bbfa8efef5d31d2a6746368c8eac12df1b47a3db9f0754f"
