entry_version = 1
name = "inbox-brew"
kind = "widget"
latest = "0.5.0"
description = "Homebrew updates and actions in EasyBar's native inbox."
categories = ["developer-tools", "inbox", "system"]

[source]
repository = "https://github.com/easybar-app/widgets"

[[versions]]
version = "0.1.0"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.1.0/inbox-brew-0.1.0.tar.gz"
sha256 = "2902150c0d9ec61f51d0d6565ac7c5778c9912c1c092a2f090675282f7389356"

[[versions]]
version = "0.1.1"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.1.1/inbox-brew-0.1.1.tar.gz"
sha256 = "7ab0d80c78757720b58f4d4108b8fe88587afc62c968f161ff229162fdaf9176"

[[versions]]
version = "0.2.0"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.2.0/inbox-brew-0.2.0.tar.gz"
sha256 = "678b84b5cbb4f4cb324e87d9d473c7f0756088b6e3e01143dbc9bf47daf7f4b1"

[[versions]]
version = "0.3.0"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.3.0/inbox-brew-0.3.0.tar.gz"
sha256 = "11fcebba8bfa34f73baecf8dc2c76b0e6add6cba0b2df9f9f4091495478b028b"

[[versions]]
version = "0.3.1"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.3.1/inbox-brew-0.3.1.tar.gz"
sha256 = "2a9de7955fd05d970592e0490ef2d3ce7b8e5b09d8f5cab884579168517accda"

[[versions]]
version = "0.3.2"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.3.2/inbox-brew-0.3.2.tar.gz"
sha256 = "4a198b3db21bd1e23963c35df7086c4ff6c854a85f14d73408e8f6bf6f40e520"

[[versions]]
version = "0.4.0"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.4.0/inbox-brew-0.4.0.tar.gz"
sha256 = "e2682747a045357730e51925e0b8889eb17717e8ec228fb799f3b74cbc11075e"

[[versions]]
version = "0.4.1"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.4.1/inbox-brew-0.4.1.tar.gz"
sha256 = "1c29c8dccfac135774b72aa52272084666af95623f088f906b23e9573f933874"

[[versions]]
version = "0.4.3"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.4.3/inbox-brew-0.4.3.tar.gz"
sha256 = "9ad111f503012225b96865f867c883bd1df66d5b3cf1c93f95a6a97f01639973"

[[versions]]
version = "0.4.4"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.4.4/inbox-brew-0.4.4.tar.gz"
sha256 = "36c8048a936c70ce6ef68ebc6322502748ca77358ae573bb2ca167ee65b1f4b6"

[[versions]]
version = "0.5.0"
archive = "https://github.com/easybar-app/widgets/releases/download/inbox-brew-v0.5.0/inbox-brew-0.5.0.tar.gz"
sha256 = "0851b5d790d2519830f0df882f61546b256e168292c5de23a991224fbacd9e96"
